/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ClientRouteImport } from './routes/client'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ClientTreeRouteImport } from './routes/client.tree'
import { Route as ClientTeamRouteImport } from './routes/client.team'
import { Route as ClientProfileRouteImport } from './routes/client.profile'
import { Route as ClientBrokerageHistoryRouteImport } from './routes/client.brokerage-history'
import { Route as AdminUploadHistoryRouteImport } from './routes/admin.upload-history'
import { Route as AdminUploadClientMasterRouteImport } from './routes/admin.upload-client-master'
import { Route as AdminUploadBrokerageRouteImport } from './routes/admin.upload-brokerage'
import { Route as AdminTreeRouteImport } from './routes/admin.tree'
import { Route as AdminPasswordRequestsRouteImport } from './routes/admin.password-requests'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminBrokerageReportRouteImport } from './routes/admin.brokerage-report'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ClientTreeRoute = ClientTreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => ClientRoute,
} as any)
const ClientTeamRoute = ClientTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ClientRoute,
} as any)
const ClientProfileRoute = ClientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ClientRoute,
} as any)
const ClientBrokerageHistoryRoute = ClientBrokerageHistoryRouteImport.update({
  id: '/brokerage-history',
  path: '/brokerage-history',
  getParentRoute: () => ClientRoute,
} as any)
const AdminUploadHistoryRoute = AdminUploadHistoryRouteImport.update({
  id: '/upload-history',
  path: '/upload-history',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUploadClientMasterRoute = AdminUploadClientMasterRouteImport.update({
  id: '/upload-client-master',
  path: '/upload-client-master',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUploadBrokerageRoute = AdminUploadBrokerageRouteImport.update({
  id: '/upload-brokerage',
  path: '/upload-brokerage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTreeRoute = AdminTreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPasswordRequestsRoute = AdminPasswordRequestsRouteImport.update({
  id: '/password-requests',
  path: '/password-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrokerageReportRoute = AdminBrokerageReportRouteImport.update({
  id: '/brokerage-report',
  path: '/brokerage-report',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/client': typeof ClientRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/admin/brokerage-report': typeof AdminBrokerageReportRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/password-requests': typeof AdminPasswordRequestsRoute
  '/admin/tree': typeof AdminTreeRoute
  '/admin/upload-brokerage': typeof AdminUploadBrokerageRoute
  '/admin/upload-client-master': typeof AdminUploadClientMasterRoute
  '/admin/upload-history': typeof AdminUploadHistoryRoute
  '/client/brokerage-history': typeof ClientBrokerageHistoryRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/team': typeof ClientTeamRoute
  '/client/tree': typeof ClientTreeRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/admin/brokerage-report': typeof AdminBrokerageReportRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/password-requests': typeof AdminPasswordRequestsRoute
  '/admin/tree': typeof AdminTreeRoute
  '/admin/upload-brokerage': typeof AdminUploadBrokerageRoute
  '/admin/upload-client-master': typeof AdminUploadClientMasterRoute
  '/admin/upload-history': typeof AdminUploadHistoryRoute
  '/client/brokerage-history': typeof ClientBrokerageHistoryRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/team': typeof ClientTeamRoute
  '/client/tree': typeof ClientTreeRoute
  '/admin': typeof AdminIndexRoute
  '/client': typeof ClientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/client': typeof ClientRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/admin/brokerage-report': typeof AdminBrokerageReportRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/password-requests': typeof AdminPasswordRequestsRoute
  '/admin/tree': typeof AdminTreeRoute
  '/admin/upload-brokerage': typeof AdminUploadBrokerageRoute
  '/admin/upload-client-master': typeof AdminUploadClientMasterRoute
  '/admin/upload-history': typeof AdminUploadHistoryRoute
  '/client/brokerage-history': typeof ClientBrokerageHistoryRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/team': typeof ClientTeamRoute
  '/client/tree': typeof ClientTreeRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/change-password'
    | '/client'
    | '/forgot-password'
    | '/login'
    | '/admin/brokerage-report'
    | '/admin/clients'
    | '/admin/password-requests'
    | '/admin/tree'
    | '/admin/upload-brokerage'
    | '/admin/upload-client-master'
    | '/admin/upload-history'
    | '/client/brokerage-history'
    | '/client/profile'
    | '/client/team'
    | '/client/tree'
    | '/admin/'
    | '/client/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/admin/brokerage-report'
    | '/admin/clients'
    | '/admin/password-requests'
    | '/admin/tree'
    | '/admin/upload-brokerage'
    | '/admin/upload-client-master'
    | '/admin/upload-history'
    | '/client/brokerage-history'
    | '/client/profile'
    | '/client/team'
    | '/client/tree'
    | '/admin'
    | '/client'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/change-password'
    | '/client'
    | '/forgot-password'
    | '/login'
    | '/admin/brokerage-report'
    | '/admin/clients'
    | '/admin/password-requests'
    | '/admin/tree'
    | '/admin/upload-brokerage'
    | '/admin/upload-client-master'
    | '/admin/upload-history'
    | '/client/brokerage-history'
    | '/client/profile'
    | '/client/team'
    | '/client/tree'
    | '/admin/'
    | '/client/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  ClientRoute: typeof ClientRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/client/tree': {
      id: '/client/tree'
      path: '/tree'
      fullPath: '/client/tree'
      preLoaderRoute: typeof ClientTreeRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/team': {
      id: '/client/team'
      path: '/team'
      fullPath: '/client/team'
      preLoaderRoute: typeof ClientTeamRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/profile': {
      id: '/client/profile'
      path: '/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof ClientProfileRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/brokerage-history': {
      id: '/client/brokerage-history'
      path: '/brokerage-history'
      fullPath: '/client/brokerage-history'
      preLoaderRoute: typeof ClientBrokerageHistoryRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/upload-history': {
      id: '/admin/upload-history'
      path: '/upload-history'
      fullPath: '/admin/upload-history'
      preLoaderRoute: typeof AdminUploadHistoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/upload-client-master': {
      id: '/admin/upload-client-master'
      path: '/upload-client-master'
      fullPath: '/admin/upload-client-master'
      preLoaderRoute: typeof AdminUploadClientMasterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/upload-brokerage': {
      id: '/admin/upload-brokerage'
      path: '/upload-brokerage'
      fullPath: '/admin/upload-brokerage'
      preLoaderRoute: typeof AdminUploadBrokerageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tree': {
      id: '/admin/tree'
      path: '/tree'
      fullPath: '/admin/tree'
      preLoaderRoute: typeof AdminTreeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/password-requests': {
      id: '/admin/password-requests'
      path: '/password-requests'
      fullPath: '/admin/password-requests'
      preLoaderRoute: typeof AdminPasswordRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/brokerage-report': {
      id: '/admin/brokerage-report'
      path: '/brokerage-report'
      fullPath: '/admin/brokerage-report'
      preLoaderRoute: typeof AdminBrokerageReportRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBrokerageReportRoute: typeof AdminBrokerageReportRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminPasswordRequestsRoute: typeof AdminPasswordRequestsRoute
  AdminTreeRoute: typeof AdminTreeRoute
  AdminUploadBrokerageRoute: typeof AdminUploadBrokerageRoute
  AdminUploadClientMasterRoute: typeof AdminUploadClientMasterRoute
  AdminUploadHistoryRoute: typeof AdminUploadHistoryRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBrokerageReportRoute: AdminBrokerageReportRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminPasswordRequestsRoute: AdminPasswordRequestsRoute,
  AdminTreeRoute: AdminTreeRoute,
  AdminUploadBrokerageRoute: AdminUploadBrokerageRoute,
  AdminUploadClientMasterRoute: AdminUploadClientMasterRoute,
  AdminUploadHistoryRoute: AdminUploadHistoryRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientBrokerageHistoryRoute: typeof ClientBrokerageHistoryRoute
  ClientProfileRoute: typeof ClientProfileRoute
  ClientTeamRoute: typeof ClientTeamRoute
  ClientTreeRoute: typeof ClientTreeRoute
  ClientIndexRoute: typeof ClientIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientBrokerageHistoryRoute: ClientBrokerageHistoryRoute,
  ClientProfileRoute: ClientProfileRoute,
  ClientTeamRoute: ClientTeamRoute,
  ClientTreeRoute: ClientTreeRoute,
  ClientIndexRoute: ClientIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  ClientRoute: ClientRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
